<?php
namespace TwentyThreeAndMe\Genomes;

class AnnotatedFile
{
    private $filename;
    private $fp;

    public function __construct($filename)
    {
        $this->filename = $filename;
        $this->fp = fopen($filename, 'w');
        $this->appendHeader();
    }

    /**
     * @return string
     */
    public function getFilename()
    {
        return $this->filename;
    }

    private function appendHeader()
    {
        $headerNames = implode("\t", ['rsid', 'chromosome', 'position', 'genotype']);
        $header =<<<EOHEADER
# File generated by InSilicoDB to mimic the 23AndMe output file';
# Index file last updated: 2014-07-23';
# $headerNames

EOHEADER;
        fwrite($this->fp, $header);
    }

    public function append($name, $chromosome, $position, $genotype)
    {
        fwrite(
            $this->fp,
            implode(
                "\t",
                [$name, $chromosome, $position, $genotype]
            ) . PHP_EOL
        );
    }

    public function close()
    {
        fclose($this->fp);
    }
}