<?php
namespace TwentyThreeAndMe\Genomes;

class AnnotatedFile
{
    private $filename;
    private $fp;
    private $annotations = [];

    public function __construct($filename)
    {
        $this->filename = $filename;
        $this->fp = fopen($filename, 'w');
        $this->appendHeader();
    }

    /**
     * @return string
     */
    public function getFilename()
    {
        return $this->filename;
    }

    private function appendHeader()
    {
        $headerNames = implode("\t", ['rsid', 'chromosome', 'position', 'genotype']);
        $header =<<<EOHEADER
# File generated by InSilicoDB to mimic the 23AndMe output file';
# Index file last updated: 2014-07-23';
# $headerNames

EOHEADER;
        fwrite($this->fp, $header);
    }

    public function append($name, $chromosome, $position, $genotype)
    {
        $this->annotations[$chromosome][$position] = implode("\t", [$name, $chromosome, $position, $genotype]);

    }

    public function close()
    {
        ksort($this->annotations, SORT_NUMERIC);
        foreach ($this->annotations as $chromosomeAnnotations) {
            ksort($chromosomeAnnotations);
            foreach ($chromosomeAnnotations as $annotation) {
                fwrite($this->fp, $annotation. PHP_EOL);
            }
        }
        fclose($this->fp);
    }
}